apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-vault-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mgmt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://github.com/Dayzpd/kustomize-vault-operator
    targetRevision: HEAD
    path: overlays/mgmt
  destination:
    name: in-cluster
    namespace: vault-operator
  ignoreDifferences: []